GEMINI_MODEL = "gemini-3.1-flash-lite-preview"  # default / fallback
MODEL_HYPOTHESIS = "gemini-3.1-flash-lite-preview"  # hypothesis generation (15 RPM)
MODEL_INTERPRET = "gemini-3.1-flash-lite-preview"  # result interpretation (15 RPM)
MODEL_DEEP_DIVE = "gemini-3.1-flash-lite-preview"  # deep dive analysis (15 RPM)
MODEL_SYNTHESIS = "gemini-3.1-flash-lite-preview"  # report writing (15 RPM)
ANALYSIS_TEMPERATURE = 0.3
CREATIVE_TEMPERATURE = 0.7
LLM_TIMEOUT = 30
MAX_ROWS = 50000
MAX_FILE_SIZE_MB = 50
MAX_COLUMNS = 50
OUTLIER_Z_THRESHOLD = 3.0
OUTLIER_IQR_MULTIPLIER = 1.5
MAX_HYPOTHESES = 6
MAX_DEEP_DIVES = 2
MAX_CHART_POINTS = 1000
SAMPLE_SIZE_FOR_PROFILE = 5  # sample values to show per column
