GEMINI_MODEL = "gemini-2.5-flash"
CONTENT_TEMPERATURE = 0.7
ANALYSIS_TEMPERATURE = 0.3
SCRAPE_TIMEOUT = 10
LLM_TIMEOUT = 30
REVISION_THRESHOLD = 7
MAX_REVISIONS = 1
CAMPAIGN_GOALS = ["Product Launch", "Brand Awareness", "Lead Generation", "Engagement"]
