GEMINI_MODEL = "gemini-2.5-flash-lite"  # default / fallback
MODEL_PARSING = "gemini-3.1-flash-lite"  # structured parsing (15 RPM)
MODEL_ANALYSIS = "gemini-2.5-flash-lite"  # gap analysis, research (10 RPM)
MODEL_EVALUATION = "gemini-3.1-flash-lite"  # ATS scoring (15 RPM)
MODEL_CREATIVE = "gemini-2.5-flash"  # resume tailoring, cover letters (5 RPM)
ANALYSIS_TEMPERATURE = 0.3
CREATIVE_TEMPERATURE = 0.7
REVISION_THRESHOLD = 7
MAX_REVISIONS = 1
SCRAPE_TIMEOUT = 8
SEARCH_RESULTS_PER_QUERY = 3
SEARCH_DELAY = 1.0
LLM_TIMEOUT = 30
MAX_CONTENT_CHARS = 2000
